name: Latest stack overflow activity
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest projects from Youtube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLXqpPMkaErFYWgIVtDNBx6wuJIzwmpUCn"